[project]
name = "user-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DulshanSiriwardhana", email = "dulshansiriwardhanaofficial@gmail.com" }
]
requires-python = ">=3.14,<3.16"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.4",
    "pydantic[email]>=2.13.4",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
    "cryptography>=42.0.0",
    "pyjwt>=2.7.0",
    "bcrypt>=4.0.0",
    "python-multipart>=0.0.9",
]


[project.scripts]
user-service = "user_service:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.vercel]
entrypoint = "src.user_service.main:app"